import type { Property } from "./types"

export const properties: Property[] = [
  {
    id: "1",
    title: "Luxury Beach Villa in Candolim",
    description:
      "Stunning 4-bedroom villa with private pool and beach access. Perfect for luxury living or investment. This magnificent property features contemporary architecture with traditional Goan elements, offering the perfect blend of modern comfort and local charm. The villa boasts spacious living areas, a gourmet kitchen, and beautifully landscaped gardens.",
    price: 25000000,
    location: "Candolim",
    type: "sale",
    propertyType: "villa",
    bedrooms: 4,
    bathrooms: 3,
    area: 3500,
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    amenities: ["Swimming Pool", "Beach Access", "Garden", "Parking", "Security", "Furnished", "AC", "WiFi"],
    featured: true,
    createdAt: "2024-01-15",
    videoWalkthrough: {
      provider: "youtube",
      url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      embedId: "dQw4w9WgXcQ",
      thumbnail: "/placeholder.svg?height=360&width=640",
    },
    floorPlan: "/placeholder.svg?height=600&width=800",
  },
  {
    id: "2",
    title: "Modern Apartment in Panaji",
    description:
      "Contemporary 2-bedroom apartment in the heart of Panaji with city views. This stylish apartment offers modern living with premium finishes and convenient access to shopping, dining, and business districts.",
    price: 8500000,
    location: "Panaji",
    type: "sale",
    propertyType: "apartment",
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    amenities: ["Elevator", "Parking", "Balcony", "Security", "AC", "Furnished"],
    featured: false,
    createdAt: "2024-01-10",
    floorPlan: "/placeholder.svg?height=600&width=800",
  },
  {
    id: "3",
    title: "Cozy House in Margao",
    description:
      "Perfect family home with 3 bedrooms and a beautiful garden. Located in a quiet residential area with easy access to schools, markets, and transportation.",
    price: 45000,
    location: "Margao",
    type: "rent",
    propertyType: "house",
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    amenities: ["Garden", "Parking", "Furnished", "AC", "Security"],
    featured: true,
    createdAt: "2024-01-12",
    videoWalkthrough: {
      provider: "vimeo",
      url: "https://vimeo.com/123456789",
      embedId: "123456789",
      thumbnail: "/placeholder.svg?height=360&width=640",
    },
  },
  {
    id: "4",
    title: "Luxury Penthouse in Baga",
    description:
      "Exclusive penthouse with panoramic views and premium amenities. This stunning property offers the ultimate in luxury living with breathtaking views of the Arabian Sea.",
    price: 35000000,
    location: "Baga",
    type: "sale",
    propertyType: "apartment",
    bedrooms: 3,
    bathrooms: 3,
    area: 2200,
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    amenities: ["Terrace", "Swimming Pool", "Gym", "Parking", "Security", "Sea View", "Furnished", "AC"],
    featured: true,
    createdAt: "2024-01-08",
    videoWalkthrough: {
      provider: "youtube",
      url: "https://www.youtube.com/watch?v=example123",
      embedId: "example123",
      thumbnail: "/placeholder.svg?height=360&width=640",
    },
    floorPlan: "/placeholder.svg?height=600&width=800",
  },
  {
    id: "5",
    title: "Studio Apartment in Calangute",
    description:
      "Compact and modern studio perfect for young professionals or vacation rental. Located close to the beach and popular restaurants.",
    price: 25000,
    location: "Calangute",
    type: "rent",
    propertyType: "apartment",
    bedrooms: 1,
    bathrooms: 1,
    area: 500,
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    amenities: ["Furnished", "AC", "Parking", "WiFi", "Beach Access"],
    featured: false,
    createdAt: "2024-01-05",
  },
  {
    id: "6",
    title: "Heritage Villa in Old Goa",
    description:
      "Restored Portuguese villa with historical charm and modern amenities. This unique property combines heritage architecture with contemporary comfort.",
    price: 18000000,
    location: "Old Goa",
    type: "sale",
    propertyType: "villa",
    bedrooms: 5,
    bathrooms: 4,
    area: 4000,
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    amenities: ["Heritage Property", "Garden", "Parking", "Restored", "AC", "Security", "WiFi"],
    featured: true,
    createdAt: "2024-01-03",
    videoWalkthrough: {
      provider: "custom",
      url: "https://kuula.co/share/heritage123",
      embedId: "heritage123",
    },
    floorPlan: "/placeholder.svg?height=600&width=800",
  },
]

export const locations = [
  "Candolim",
  "Panaji",
  "Margao",
  "Baga",
  "Calangute",
  "Old Goa",
  "Anjuna",
  "Arambol",
  "Ponda",
  "Vasco da Gama",
]

export const propertyTypes = [
  { value: "apartment", label: "Apartment" },
  { value: "villa", label: "Villa" },
  { value: "house", label: "House" },
  { value: "commercial", label: "Commercial" },
  { value: "land", label: "Plot/Land" },
  { value: "penthouse", label: "Penthouse" },
  { value: "studio", label: "Studio" },
  { value: "duplex", label: "Duplex" },
  { value: "bungalow", label: "Bungalow" },
  { value: "farmhouse", label: "Farmhouse" },
  { value: "beach_house", label: "Beach House" },
  { value: "townhouse", label: "Townhouse" },
  { value: "condominium", label: "Condominium" },
  { value: "office_space", label: "Office Space" },
  { value: "retail_space", label: "Retail Space" },
  { value: "warehouse", label: "Warehouse" },
  { value: "industrial", label: "Industrial" }
]
